#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace One.Services.API.Gateway.Controllers.Suite.Restaurant
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Secundario")]
	public partial class SecundarioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertPension(Pension instance);
    partial void UpdatePension(Pension instance);
    partial void DeletePension(Pension instance);
    #endregion
		
		public SecundarioDataContext() : 
				base(global::One.Services.API.Gateway.Properties.Settings.Default.SecundarioConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SecundarioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SecundarioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SecundarioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SecundarioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Pension> Pension
		{
			get
			{
				return this.GetTable<Pension>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pension")]
	public partial class Pension : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _ResNro;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Comida;
		
		private System.Nullable<int> _Cantidad;
		
		private string _Nro;
		
		private System.Nullable<bool> _Usado;
		
		private System.Nullable<System.DateTime> _FechaUso;
		
		private System.Nullable<System.DateTime> _ValDesde;
		
		private System.Nullable<System.DateTime> _ValHasta;
		
		private System.Nullable<int> _Operation;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnResNroChanging(System.Nullable<int> value);
    partial void OnResNroChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnComidaChanging(string value);
    partial void OnComidaChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void OnNroChanging(string value);
    partial void OnNroChanged();
    partial void OnUsadoChanging(System.Nullable<bool> value);
    partial void OnUsadoChanged();
    partial void OnFechaUsoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaUsoChanged();
    partial void OnValDesdeChanging(System.Nullable<System.DateTime> value);
    partial void OnValDesdeChanged();
    partial void OnValHastaChanging(System.Nullable<System.DateTime> value);
    partial void OnValHastaChanged();
    partial void OnOperationChanging(System.Nullable<int> value);
    partial void OnOperationChanged();
    #endregion
		
		public Pension()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResNro", DbType="Int")]
		public System.Nullable<int> ResNro
		{
			get
			{
				return this._ResNro;
			}
			set
			{
				if ((this._ResNro != value))
				{
					this.OnResNroChanging(value);
					this.SendPropertyChanging();
					this._ResNro = value;
					this.SendPropertyChanged("ResNro");
					this.OnResNroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comida", DbType="NVarChar(255)")]
		public string Comida
		{
			get
			{
				return this._Comida;
			}
			set
			{
				if ((this._Comida != value))
				{
					this.OnComidaChanging(value);
					this.SendPropertyChanging();
					this._Comida = value;
					this.SendPropertyChanged("Comida");
					this.OnComidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nro", DbType="NVarChar(255)")]
		public string Nro
		{
			get
			{
				return this._Nro;
			}
			set
			{
				if ((this._Nro != value))
				{
					this.OnNroChanging(value);
					this.SendPropertyChanging();
					this._Nro = value;
					this.SendPropertyChanged("Nro");
					this.OnNroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usado", DbType="Bit")]
		public System.Nullable<bool> Usado
		{
			get
			{
				return this._Usado;
			}
			set
			{
				if ((this._Usado != value))
				{
					this.OnUsadoChanging(value);
					this.SendPropertyChanging();
					this._Usado = value;
					this.SendPropertyChanged("Usado");
					this.OnUsadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUso", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaUso
		{
			get
			{
				return this._FechaUso;
			}
			set
			{
				if ((this._FechaUso != value))
				{
					this.OnFechaUsoChanging(value);
					this.SendPropertyChanging();
					this._FechaUso = value;
					this.SendPropertyChanged("FechaUso");
					this.OnFechaUsoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValDesde", DbType="DateTime")]
		public System.Nullable<System.DateTime> ValDesde
		{
			get
			{
				return this._ValDesde;
			}
			set
			{
				if ((this._ValDesde != value))
				{
					this.OnValDesdeChanging(value);
					this.SendPropertyChanging();
					this._ValDesde = value;
					this.SendPropertyChanged("ValDesde");
					this.OnValDesdeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValHasta", DbType="DateTime")]
		public System.Nullable<System.DateTime> ValHasta
		{
			get
			{
				return this._ValHasta;
			}
			set
			{
				if ((this._ValHasta != value))
				{
					this.OnValHastaChanging(value);
					this.SendPropertyChanging();
					this._ValHasta = value;
					this.SendPropertyChanged("ValHasta");
					this.OnValHastaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operation", DbType="Int")]
		public System.Nullable<int> Operation
		{
			get
			{
				return this._Operation;
			}
			set
			{
				if ((this._Operation != value))
				{
					this.OnOperationChanging(value);
					this.SendPropertyChanging();
					this._Operation = value;
					this.SendPropertyChanged("Operation");
					this.OnOperationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
