#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace One.Services.API.Gateway.Controllers.Suite.Restaurant
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Secundario")]
	public partial class SecundarioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public SecundarioDataContext() : 
				base(global::One.Services.API.Gateway.Properties.Settings.Default.SecundarioConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SecundarioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SecundarioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SecundarioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SecundarioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Pension> Pension
		{
			get
			{
				return this.GetTable<Pension>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pension")]
	public partial class Pension
	{
		
		private int _Id;
		
		private System.Nullable<int> _ResNro;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Comida;
		
		private System.Nullable<int> _Cantidad;
		
		private string _Nro;
		
		private System.Nullable<bool> _Usado;
		
		private System.Nullable<System.DateTime> _FechaUso;
		
		private System.Nullable<System.DateTime> _ValDesde;
		
		private System.Nullable<System.DateTime> _ValHasta;
		
		private System.Nullable<int> _Operation;
		
		public Pension()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResNro", DbType="Int")]
		public System.Nullable<int> ResNro
		{
			get
			{
				return this._ResNro;
			}
			set
			{
				if ((this._ResNro != value))
				{
					this._ResNro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comida", DbType="NVarChar(255)")]
		public string Comida
		{
			get
			{
				return this._Comida;
			}
			set
			{
				if ((this._Comida != value))
				{
					this._Comida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nro", DbType="NVarChar(255)")]
		public string Nro
		{
			get
			{
				return this._Nro;
			}
			set
			{
				if ((this._Nro != value))
				{
					this._Nro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usado", DbType="Bit")]
		public System.Nullable<bool> Usado
		{
			get
			{
				return this._Usado;
			}
			set
			{
				if ((this._Usado != value))
				{
					this._Usado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUso", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaUso
		{
			get
			{
				return this._FechaUso;
			}
			set
			{
				if ((this._FechaUso != value))
				{
					this._FechaUso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValDesde", DbType="DateTime")]
		public System.Nullable<System.DateTime> ValDesde
		{
			get
			{
				return this._ValDesde;
			}
			set
			{
				if ((this._ValDesde != value))
				{
					this._ValDesde = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValHasta", DbType="DateTime")]
		public System.Nullable<System.DateTime> ValHasta
		{
			get
			{
				return this._ValHasta;
			}
			set
			{
				if ((this._ValHasta != value))
				{
					this._ValHasta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operation", DbType="Int")]
		public System.Nullable<int> Operation
		{
			get
			{
				return this._Operation;
			}
			set
			{
				if ((this._Operation != value))
				{
					this._Operation = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
